ktor:
  application:
    modules:
      - me.nooneboss.ApplicationKt.module
  deployment:
    port: 8081
jwt:
  secret: "diplomrpgASFDKF13RKSDKF00$21MSDKASDFR$"

databases:
  postgresql:
    address: localhost
    port: 5432
  mongo:
    address: localhost
    port: 27017