ktor:
  application:
    modules:
      - me.nooneboss.ApplicationKt.module
  deployment:
    port: 8081
jwt:
  secret: "diplomrpgASFDKF13RKSDKF00$21MSDKASDFR$"

databases:
  mongodb:
    user: nooneboss
    password: admin
    address: 127.0.0.1
    port: 27017